sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/debian-buster-nim-base
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/debian-buster-nim-base run sh ./cibuild.sh
